copyright: Copyright &copy; 2015-2020 THOORENS Bruno - BSD licence
docs_dir: docs
nav:
- Overview: index.md
- API: api.md
- Core: core.md
repo_name: GitHub
repo_url: https://github.com/Moustikitos/Tyf
site_name: The Tyf Project
theme:
  name: mkdocs
  nav_style: light
